name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Weekly security scan on Sundays at 3:30 AM UTC
    - cron: '30 3 * * 0'
  workflow_dispatch:

env:
  NODE_VERSION: '20'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  javascript-security:
    name: JavaScript Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: |
        npm audit --audit-level=moderate --output=json > npm-audit-results.json || true
        echo "NPM Audit completed"

    - name: Convert npm audit to SARIF
      run: |
        # Create a simple SARIF file from npm audit results
        cat > npm-audit.sarif << 'EOF'
        {
          "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
          "version": "2.1.0",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "npm audit",
                  "version": "1.0.0"
                }
              },
              "results": []
            }
          ]
        }
        EOF

    - name: Upload npm audit results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: npm-audit.sarif

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run ESLint security rules
      run: |
        npx eslint . --ext .js,.ts,.vue --format json --output-file eslint-results.json || true

    - name: Check for security-sensitive patterns
      run: |
        echo "Checking for common security issues..."
        # Check for potential XSS vulnerabilities
        grep -r "innerHTML\|outerHTML\|insertAdjacentHTML" src/ || echo "No innerHTML usage found"
        # Check for eval usage
        grep -r "eval(" src/ || echo "No eval usage found"
        # Check for dangerous imports
        grep -r "dangerouslySetInnerHTML" src/ || echo "No dangerouslySetInnerHTML usage found"

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Run GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations
      with:
        args: --no-git --redact

    - name: Upload GitLeaks results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        queries: +security-and-quality

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for CodeQL
      run: npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [javascript-security, secret-scanning, codeql]
    if: always()
    
    steps:
    - name: Security scan summary
      run: |
        echo "# Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Scan Status" >> $GITHUB_STEP_SUMMARY
        echo "- JavaScript Security: ${{ needs.javascript-security.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Secret Scanning: ${{ needs.secret-scanning.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- CodeQL: ${{ needs.codeql.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📊 View detailed results in the Security tab" >> $GITHUB_STEP_SUMMARY