name: Security Scan

on:
  schedule:
    # Weekly security scan on Sundays at 3:30 AM UTC
    - cron: '30 3 * * 0'
  workflow_dispatch:

jobs:
  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'javascript'
      node-version: '20'
    secrets: inherit